version: '3'

#volumes:
  #postgres_data:
      #driver: local

services:
  #postgres:
    #image: postgres
    #volumes:
      #- postgres_data:/var/lib/postgresql/data
    #environment:
      #POSTGRES_DB: postgres
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
    depends_on:
      - rabbitmq
    ports:
      - 8001:8000
    volumes:
      - .:/install

  rabbitmq:
    image: rabbitmq:latest

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
        WORKER_NAME: "worker-from-compose"
    volumes:
      - .:/install
    depends_on:
      - rabbitmq
