apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-server
  labels:
    app: rabbitmq-server
spec:
  containers:
  - name: rabbitmq-server
    image: rabbitmq:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
   name: rabbitmq
spec:
   selector:
     app: rabbitmq-server
   ports:
     - protocol: TCP
       port: 5672
       targetPort: 5672
