apiVersion: v1
kind: Pod
metadata:
  name: spike-api
  labels:
    app: api
spec:
  containers:
  - name: spike-api
    image: instances-management_api
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8000
      hostPort: 80
